[features]
seeds = false
[programs.localnet]
nft_breeding = "NFTBfAcFhBb8yqNvYiN8RPQfr5KrVuHGK7pj61EiVnZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/initialize.ts"
compute = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/compute.ts"
mintChild = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/mintChild.ts"
updateUri = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/updateUri.ts"
