[features]
seeds = false
[programs.localnet]
nft_breeding = "9U1zSoU2vK8UBDeT8a3YEaF9Nvb7uE1mF4hKYy4NTnTB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
